version: "3.8"
services:
  db:
  # no changes for the database

  backend:
    volumes:
      - ./backend/src:/app/src
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev
